import { Composition, registerRoot } from 'remotion';
import { IntroVideo } from './IntroVideo';
import { TimelineVideo } from './TimelineVideo';
import { LabShowcaseVideo } from './LabShowcaseVideo';
import { SkillsReelVideo } from './SkillsReelVideo';
import { PodcastTeaserVideo } from './PodcastTeaserVideo';
import { AnimateDiffVideo } from './AnimateDiffVideo';
import { GenericShowcaseVideo } from './GenericShowcaseVideo';
import { MasterReel } from './MasterReel';
import { ThreeDShowcaseVideo } from './ThreeDShowcaseVideo';
import { AudiogramDemo } from './AudiogramDemo';
import './style.css';

export const RemotionRoot: React.FC = () => {
    return (
        <>
            <Composition
                id="AudiogramDemo"
                component={AudiogramDemo}
                durationInFrames={180}
                fps={30}
                width={1920}
                height={1080}
            />
            <Composition
                id="ThreeDInfrastructure"
                component={ThreeDShowcaseVideo}
                durationInFrames={300}
                fps={30}
                width={1920}
                height={1080}
            />
            <Composition
                id="MasterReel"
                component={MasterReel}
                durationInFrames={1050}
                fps={30}
                width={1920}
                height={1080}
            />
            <Composition
                id="ThreeBodyShowcase"
                component={GenericShowcaseVideo}
                durationInFrames={300}
                fps={30}
                width={1920}
                height={1080}
                defaultProps={{
                    imageSrc: '3body.jpg',
                    audioSrc: 'music.mp3',
                    title: 'The Three-Body Problem',
                    subtitle: 'Celestial Mechanics & Chaos',
                    accentColor: '#ff3e3e'
                }}
            />
            <Composition
                id="VRRealityShowcase"
                component={GenericShowcaseVideo}
                durationInFrames={300}
                fps={30}
                width={1920}
                height={1080}
                defaultProps={{
                    imageSrc: 'vr-reality.png',
                    audioSrc: 'music.mp3',
                    title: 'Virtual Frontiers',
                    subtitle: 'Experiencing the Unreal',
                    accentColor: '#00fbff'
                }}
            />
            <Composition
                id="EngineeringShowcase"
                component={GenericShowcaseVideo}
                durationInFrames={300}
                fps={30}
                width={1920}
                height={1080}
                defaultProps={{
                    imageSrc: 'build.jpg',
                    audioSrc: 'music.mp3',
                    title: 'Precision Build',
                    subtitle: 'Engineering the Future',
                    accentColor: '#ffa200'
                }}
            />
            <Composition
                id="AIArtShowcase"
                component={GenericShowcaseVideo}
                durationInFrames={300}
                fps={30}
                width={1920}
                height={1080}
                defaultProps={{
                    imageSrc: 'ai-art.jpg',
                    audioSrc: 'music.mp3',
                    title: 'Neural Aesthetics',
                    subtitle: 'Generated by Gemini',
                    accentColor: '#bc00ff'
                }}
            />
            <Composition
                id="NikeEnergyShowcase"
                component={GenericShowcaseVideo}
                durationInFrames={300}
                fps={30}
                width={1920}
                height={1080}
                defaultProps={{
                    imageSrc: 'nike.jpg',
                    audioSrc: 'music.mp3',
                    title: 'Dynamic Energy',
                    subtitle: 'Just Do It',
                    accentColor: '#ffffff'
                }}
            />
            <Composition
                id="AnimateDiffVideo"
                component={AnimateDiffVideo}
                durationInFrames={300}
                fps={30}
                width={1920}
                height={1080}
            />
            <Composition
                id="IntroVideo"
                component={IntroVideo}
                durationInFrames={450}
                fps={30}
                width={1920}
                height={1080}
            />
            <Composition
                id="TimelineVideo"
                component={TimelineVideo}
                durationInFrames={900}
                fps={30}
                width={1920}
                height={1080}
            />
            <Composition
                id="LabShowcaseVideo"
                component={LabShowcaseVideo}
                durationInFrames={600}
                fps={30}
                width={1920}
                height={1080}
            />
            <Composition
                id="SkillsReelVideo"
                component={SkillsReelVideo}
                durationInFrames={600}
                fps={30}
                width={1920}
                height={1080}
            />
            <Composition
                id="PodcastTeaserVideo"
                component={PodcastTeaserVideo}
                durationInFrames={450}
                fps={30}
                width={1920}
                height={1080}
            />
        </>
    );
};

registerRoot(RemotionRoot);
